Repository UKHomeOffice/engineering-guidance-and-standards, pull requests merged in 2023-06, with the labels that each got.

#114 Updates x-govuk/govuk-eleventy-plugin to 5.0.1
  package-lock.json
Labels: bug, dependencies

#111 Added decision record with details of enabling secret scanning.
  .eleventyignore
  technical-docs/architecture-decision-records/technical-decision-log.md
Labels: documentation

#116 Add dependancy vulnerability scanning
  .github/dependabot.yml
  technical-docs/architecture-decision-records/technical-decision-log.md
Labels: enhancement

#118 Updated header UI
  .eleventy.js
  docs/assets/logos/ho_logo.svg
  docs/tags.md
  index.md
  styles/base.scss
Labels: enhancement

#119 Addition of alpha banner with link to feedback survey
  .eleventy.js
  _includes/layouts/base.njk
  _includes/layouts/collection.njk
  _includes/layouts/page.njk
  _includes/layouts/post.njk
  _includes/layouts/product.njk
  _includes/layouts/search-index.njk
  _includes/layouts/shared/related.njk
  _includes/layouts/sitemap.njk
  _includes/layouts/sub-navigation.njk
  _includes/layouts/tag.njk
  _includes/layouts/tags.njk
  _includes/macros/feedbackBanner.njk
  styles/base.scss
Labels: enhancement

#63 Create the design for success principle
  docs/principles/design-for-success.md
Labels: principle, content, Software design

#80 Ways of working - Minimal documentation standards
  docs/standards/minimal-documentation-set-for-a-product.md
Labels: documentation, standard, content, Ways of working

#143 Added link to GitHub repository in footer
  .eleventy.js
Labels: enhancement
